services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: t36
      POSTGRES_PASSWORD: "eETV_D7elbpv3sjx0Z67FJdLZdypwMsi"
    volumes:
      - t36_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "kYS7Q5przhg9Vo6FnEVotUesLt0eFGHC"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: t36_test
      POSTGRES_PASSWORD: "4rs9waOyZ-aw_qspaAPJfObDFcng2Rr8"
    volumes:
      - t36_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "HUaYa1RJedRkwr-yKAFG1WcTdVDRVD_l"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  t36_data:
  t36_test_data:
