# manifest: startProject
name: t36_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 3.0.0-rc.3
  serverpod_auth_server: ^3.0.0-rc.3
  minio: ^3.5.8
  uuid: ^4.5.1
  http: ^1.5.0


dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 3.0.0-rc.3

