# manifest: startProject
name: t36_admin
description: "Flutter Project"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.10.0"

dependencies:
# common_package:
#   path: ../Packages/common_package
# simple_storage:
#   path: ../Packages/simple_storage  
# ui_kit:
#   path: ../Packages/ui_kit
  collection: ^1.19.1
  serverpod_flutter: 3.0.0-rc.3
  t36_client:
    path: ../t36_client
  
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8

  intl: ^0.20.2
  
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  hooks_riverpod: ^3.0.3
  
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  
  go_router: ^17.0.0

  package_info_plus: ^9.0.0
  talker_flutter: ^5.1.3
  talker_riverpod_logger: ^5.1.3

  chopper: ^8.1.0

  drift: ^2.26.0
  # drift_flutter: ^0.2.4
  
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_dotenv: ^6.0.0

  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  serverpod_auth_email_flutter: ^3.0.0-rc.3
  serverpod_auth_client: ^3.0.0-rc.3
  serverpod_auth_shared_flutter: ^3.0.0-rc.3
  logger: ^2.6.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  riverpod_generator: ^3.0.3
  drift_dev: ^2.26.0
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  mockito: ^5.4.5
  
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - .env
