

apiVersion: batch/v1
kind: Job
metadata:
  name: serverpod-migration-job-t36
spec:
  template:
    spec:
      imagePullSecrets:
      - name: timeweb-registry-secret
      containers:
      - name: migrator-t36
        image: ...registry.twcstorage.ru/t36-server:latest
        command: ["/usr/local/bin/server", "--apply-migrations", "--mode", "production", "--role", "maintenance"]

        envFrom:
        - configMapRef:
            name: serverpod-config-t36
        env:
        - name: SERVERPOD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-t36
              key: database-password
        - name: SERVERPOD_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-t36
              key: redis-password
        - name: SERVERPOD_SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-t36
              key: service-secret
      restartPolicy: Never
  backoffLimit: 2
    